<#
.SYNOPSIS
  Generate strong secrets for .env on Windows.

.DESCRIPTION
  Produces a ready-to-edit .env at the repo root:
    - DB_USER fixed to ai_admin
    - DB_PASS is 32-char URL-safe random
    - WEBUI_SECRET_KEY is 48-char URL-safe random
    - leaves NEWAPI_MASTER_KEY empty (filled after first NewAPI bootstrap)
    - leaves CF_TUNNEL_TOKEN empty (paste from Cloudflare dashboard)
    - copies all other deployment settings from .env.example

.USAGE
  pwsh ./scripts/gen-secrets.ps1          # creates .env (refuses to overwrite)
  pwsh ./scripts/gen-secrets.ps1 -Force   # overwrites existing .env
#>

[CmdletBinding()]
param(
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

$root = Resolve-Path (Join-Path $PSScriptRoot '..')
$envPath = Join-Path $root '.env'
$examplePath = Join-Path $root '.env.example'

if ((Test-Path $envPath) -and -not $Force) {
    Write-Host "[skip] .env already exists at $envPath — use -Force to overwrite." -ForegroundColor Yellow
    exit 1
}

function New-UrlSafePassword {
    param([int]$Length = 32)
    $alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789-_'
    $bytes = New-Object byte[] $Length
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    -join ($bytes | ForEach-Object { $alphabet[$_ % $alphabet.Length] })
}

$dbUser = 'ai_admin'
$dbPass = New-UrlSafePassword -Length 32
$webuiSecret = New-UrlSafePassword -Length 48

if (-not (Test-Path $examplePath)) {
    throw ".env.example not found at $examplePath"
}

$template = Get-Content -Path $examplePath -Raw -Encoding UTF8
$template = $template -replace 'DB_USER=.*', "DB_USER=$dbUser"
$template = $template -replace 'DB_PASS=.*', "DB_PASS=$dbPass"
$template = $template -replace 'WEBUI_SECRET_KEY=.*', "WEBUI_SECRET_KEY=$webuiSecret"
$template = "# Generated by scripts/gen-secrets.ps1 at $(Get-Date -Format o)`n# DO NOT commit this file.`n`n$template"

Set-Content -Path $envPath -Value $template -Encoding UTF8 -NoNewline
Write-Host "[ok] wrote $envPath" -ForegroundColor Green
Write-Host "     DB_USER=$dbUser"
Write-Host "     DB_PASS=<32-char random, hidden>"
Write-Host "     WEBUI_SECRET_KEY=<48-char random, hidden>"
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Open .env and fill WEBUI_URL, hostnames, and CF_TUNNEL_TOKEN."
Write-Host "  2. Keep NEWAPI_MASTER_KEY empty for now — fill after first NewAPI bring-up."
Write-Host "  3. Commit only public templates; never commit .env."
